---
- name: Install ntp
  yum: state=present name=ntp

- name: Install wget
  yum: state=present name=wget

- name: Install tree
  yum: state=present name=tree

- name: Install telnet
  yum: state=present name=telnet

- name: Install nmap
  yum: state=present name=nmap

- name: Install man
  yum: state=present name=man

- name: Install manual pages
  yum: state=present name=man-pages

- name: Install locate
  yum: state=present name=mlocate

- name: Install vim
  yum: state=present name=vim

- name: Install elinks text mode web browser
  yum: state=present name=elinks

- name: Install mount.nfs and showmount etc for using NFSGateway to access HDFS
  yum: state=present name=nfs-utils

- name: Install java
  yum: state=present name=java-1.8.0-openjdk-headless.x86_64

- name: start ntp deamon
  service: name=ntpd state=started enabled=yes

- name: stop iptables firewall
  service: name=iptables state=stopped enabled=no

- name: modify sysctl.conf
  lineinfile: dest=/etc/sysctl.conf line="net.ipv6.conf.all.disable_ipv6 = 1"

- name: modify sysctl.conf
  lineinfile: dest=/etc/sysctl.conf line="net.ipv6.conf.default.disable_ipv6 = 1"

- name: modify sysctl.conf
  lineinfile: dest=/etc/sysctl.conf line="net.ipv6.conf.lo.disable_ipv6 = 1"

- name: reload kernel settings
  shell: 'sysctl -e -p'

- name: disable huge page support
  shell: 'echo never > /sys/kernel/mm/transparent_hugepage/enabled'

- name: modify hostsfile
  lineinfile: dest=/etc/hosts regexp='^127.0.0.1' state=present line="127.0.0.1 localhost localhost.localdomain localhost4 localhost4.localdomain4"

- name: modify hostsfile
  lineinfile: dest=/etc/hosts line="192.168.100.10 master.locallab.com master"

- name: modify hostsfile
  lineinfile: dest=/etc/hosts line="192.168.100.20 slave1.locallab.com slave1"

- name: modify hostsfile
  lineinfile: dest=/etc/hosts line="192.168.100.30 slave2.locallab.com slave2"
